#!/usr/bin/env bash
#
# Adopt the EXISTING DigitalOcean infrastructure into Terraform state.
# This imports the live droplet, DNS records and firewall — it does NOT create
# anything. Run it once, from the terraform/ directory, with your DO token in the
# environment (never paste the token into a chat or commit it):
#
#   export DIGITALOCEAN_TOKEN=dop_v1_xxxxxxxx
#   ./import.sh                       # uses defaults: andreasgabel.dk / portfolio
#   ./import.sh <domain> <droplet>    # or override
#
# Safe to re-run: resources already in state are skipped. Ends with `terraform plan`,
# which should report no changes once everything is adopted.
set -euo pipefail

TOKEN="${DIGITALOCEAN_TOKEN:-${TF_VAR_do_token:-}}"
if [ -z "$TOKEN" ]; then
  echo "ERROR: set your DigitalOcean token first, e.g.:" >&2
  echo "  export DIGITALOCEAN_TOKEN=dop_v1_xxxxxxxx" >&2
  exit 1
fi
export TF_VAR_do_token="$TOKEN"

DOMAIN="${1:-andreasgabel.dk}"
DROPLET_NAME="${2:-portfolio}"

command -v terraform >/dev/null || { echo "ERROR: terraform not found on PATH." >&2; exit 1; }
[ -d .terraform ] || terraform init -input=false >/dev/null

echo "==> Discovering live resources via the DigitalOcean API..."
DISCOVERY="$(python3 - "$TOKEN" "$DOMAIN" "$DROPLET_NAME" <<'PY'
import json, sys, urllib.request, urllib.error
token, domain, dname = sys.argv[1], sys.argv[2], sys.argv[3]

def api(path):
    req = urllib.request.Request("https://api.digitalocean.com/v2" + path,
                                 headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(req) as r:
        return json.load(r)

try:
    droplet = next((d for d in api("/droplets?per_page=200")["droplets"]
                    if d["name"] == dname), None)
    if not droplet:
        print("echo 'ERROR: no droplet named %s found in this account'; exit 1" % dname)
        sys.exit(0)
    ip = next((n["ip_address"] for n in droplet["networks"]["v4"]
               if n["type"] == "public"), "")
    recs = api("/domains/%s/records?per_page=200" % domain)["domain_records"]
    root = next((r for r in recs if r["type"] == "A" and r["name"] == "@"), None)
    www = next((r for r in recs if r["type"] == "A" and r["name"] == "www"), None)
    fw = next((f for f in api("/firewalls?per_page=200")["firewalls"]
               if droplet["id"] in f.get("droplet_ids", []) or f["name"] == dname + "-fw"), None)
    keys = [k["name"] for k in api("/account/keys?per_page=200")["ssh_keys"]]

    print("DROPLET_ID=%s" % droplet["id"])
    print("REGION=%s" % droplet["region"]["slug"])
    print("SIZE=%s" % droplet["size_slug"])
    print("DROPLET_IP=%s" % ip)
    print("ROOT_ID=%s" % (root["id"] if root else ""))
    print("WWW_ID=%s" % (www["id"] if www else ""))
    print("FW_ID=%s" % (fw["id"] if fw else ""))
    print("SSH_KEYS='%s'" % ",".join(keys))
except urllib.error.HTTPError as e:
    print("echo 'ERROR: DigitalOcean API returned HTTP %s — check your token'; exit 1" % e.code)
except Exception as e:  # noqa
    print("echo 'ERROR: discovery failed: %s'; exit 1" % str(e).replace("'", ""))
PY
)"
eval "$DISCOVERY"

echo "    droplet : $DROPLET_NAME ($DROPLET_ID)  region=$REGION  size=$SIZE  ip=$DROPLET_IP"
echo "    records : @=${ROOT_ID:-<none>}  www=${WWW_ID:-<none>}"
echo "    firewall: ${FW_ID:-<none — will be created by apply>}"
echo "    ssh keys: $SSH_KEYS"

# Generate a starter terraform.tfvars (region/size pre-filled) if you don't have one.
if [ ! -f terraform.tfvars ]; then
  SSH_DEFAULT=""
  case "$SSH_KEYS" in *,*) ;; *) SSH_DEFAULT="$SSH_KEYS" ;; esac
  {
    echo "# Auto-generated by import.sh — token comes from the environment, not this file."
    echo "ssh_key_name = \"${SSH_DEFAULT}\"   # pick one of: $SSH_KEYS"
    echo "region       = \"$REGION\""
    echo "droplet_size = \"$SIZE\""
  } > terraform.tfvars
  echo "==> Wrote terraform.tfvars (region/size match the live droplet)."
  if [ -z "$SSH_DEFAULT" ]; then
    echo "    Multiple SSH keys exist — edit ssh_key_name in terraform.tfvars, then re-run." >&2
    exit 1
  fi
fi

imported() { terraform state list 2>/dev/null | grep -qx "$1"; }
do_import() {
  local addr="$1" id="$2"
  if [ -z "$id" ]; then echo "==> skip $addr (not found — apply will create it)"; return; fi
  if imported "$addr"; then echo "==> already in state: $addr"; return; fi
  echo "==> importing $addr ($id)"
  terraform import "$addr" "$id"
}

do_import digitalocean_droplet.portfolio   "$DROPLET_ID"
do_import digitalocean_domain.portfolio    "$DOMAIN"
do_import digitalocean_record.root         "${ROOT_ID:+$DOMAIN,$ROOT_ID}"
do_import digitalocean_record.www          "${WWW_ID:+$DOMAIN,$WWW_ID}"
do_import digitalocean_firewall.portfolio  "$FW_ID"

echo ""
echo "==> terraform plan (expect NO changes, or only the firewall being created):"
terraform plan
