#!/usr/bin/env bash
#
# Adopt the EXISTING DigitalOcean droplet (and its cloud firewall, if any) into
# Terraform state. This imports — it does NOT create anything. DNS for the site
# is hosted outside DigitalOcean, so it is not managed by Terraform.
#
# Run once, from the terraform/ directory, with your DO token in the environment
# (never paste the token into a chat or commit it):
#
#   export DIGITALOCEAN_TOKEN=dop_v1_xxxxxxxx
#   ./import.sh                 # uses the default droplet name "portfolio"
#   ./import.sh <droplet-name>  # or pass the real name
#
# Safe to re-run: resources already in state are skipped. Ends with `terraform
# plan` — the droplet should show no changes; the firewall is created if absent.
set -euo pipefail

TOKEN="${DIGITALOCEAN_TOKEN:-${TF_VAR_do_token:-}}"
if [ -z "$TOKEN" ]; then
  echo "ERROR: set your DigitalOcean token first, e.g.:" >&2
  echo "  export DIGITALOCEAN_TOKEN=dop_v1_xxxxxxxx" >&2
  exit 1
fi
export TF_VAR_do_token="$TOKEN"

DROPLET_NAME="${1:-portfolio}"

command -v terraform >/dev/null || { echo "ERROR: terraform not found on PATH." >&2; exit 1; }
[ -d .terraform ] || terraform init -input=false >/dev/null

echo "==> Discovering the droplet and firewall via the DigitalOcean API..."
DISCOVERY="$(python3 - "$TOKEN" "$DROPLET_NAME" <<'PY'
import json, sys, urllib.request, urllib.error
token, dname = sys.argv[1], sys.argv[2]

def api(path):
    req = urllib.request.Request("https://api.digitalocean.com/v2" + path,
                                 headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(req) as r:
        return json.load(r)

try:
    droplets = api("/droplets?per_page=200")["droplets"]
    d = next((x for x in droplets if x["name"] == dname), None)
    if not d:
        names = ", ".join(x["name"] for x in droplets) or "(none)"
        print("echo 'ERROR: no droplet named \"%s\" in this account.'" % dname)
        print("echo 'Droplets found: %s'" % names)
        print("echo 'Re-run with the real name:  ./import.sh <droplet-name>'")
        print("exit 1")
        sys.exit(0)
    ip = next((n["ip_address"] for n in d["networks"]["v4"] if n["type"] == "public"), "")
    fw = next((f for f in api("/firewalls?per_page=200")["firewalls"]
               if d["id"] in f.get("droplet_ids", []) or f["name"] == dname + "-fw"), None)
    keys = [k["name"] for k in api("/account/keys?per_page=200")["ssh_keys"]]
    print("DROPLET_ID=%s" % d["id"])
    print("REGION=%s" % d["region"]["slug"])
    print("SIZE=%s" % d["size_slug"])
    print("DROPLET_IP=%s" % ip)
    print("FW_ID=%s" % (fw["id"] if fw else ""))
    print("SSH_KEYS='%s'" % ",".join(keys))
except urllib.error.HTTPError as e:
    print("echo 'ERROR: DigitalOcean API returned HTTP %s — check your token'; exit 1" % e.code)
except Exception as e:  # noqa
    print("echo 'ERROR: discovery failed: %s'; exit 1" % str(e).replace("'", ""))
PY
)"
eval "$DISCOVERY"

echo "    droplet : $DROPLET_NAME ($DROPLET_ID)  region=$REGION  size=$SIZE  ip=$DROPLET_IP"
echo "    firewall: ${FW_ID:-<none — apply will create it>}"
echo "    ssh keys: $SSH_KEYS"

# Generate a starter terraform.tfvars (name/region/size pre-filled) if absent.
if [ ! -f terraform.tfvars ]; then
  SSH_DEFAULT=""
  case "$SSH_KEYS" in *,*) ;; *) SSH_DEFAULT="$SSH_KEYS" ;; esac
  {
    echo "# Auto-generated by import.sh — token comes from the environment, not this file."
    echo "ssh_key_name = \"${SSH_DEFAULT}\"   # one of: $SSH_KEYS"
    echo "droplet_name = \"$DROPLET_NAME\""
    echo "region       = \"$REGION\""
    echo "droplet_size = \"$SIZE\""
  } > terraform.tfvars
  echo "==> Wrote terraform.tfvars (name/region/size match the live droplet)."
  if [ -z "$SSH_DEFAULT" ]; then
    echo "    Multiple SSH keys exist — set ssh_key_name in terraform.tfvars, then re-run." >&2
    exit 1
  fi
fi

imported() { terraform state list 2>/dev/null | grep -qx "$1"; }
do_import() {
  local addr="$1" id="$2"
  if [ -z "$id" ]; then echo "==> skip $addr (not found — apply will create it)"; return; fi
  if imported "$addr"; then echo "==> already in state: $addr"; return; fi
  echo "==> importing $addr ($id)"
  terraform import "$addr" "$id"
}

do_import digitalocean_droplet.portfolio  "$DROPLET_ID"
do_import digitalocean_firewall.portfolio "$FW_ID"

echo ""
echo "==> terraform plan (the droplet should show NO changes; the firewall is created if absent):"
terraform plan
